on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  check_nbn:
    name: Check NBN status
    runs-on: ubuntu-latest
    env:
      LOC_ID: ${{ secrets.LOC_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: pip install
        run: pip3 install -r requirements.txt
      - name: Check NBN status
        run: python3 nbn-check.py